#include "sys/types.h"
#include "unistd.h"
#include "stdlib.h"
#include "signal.h"
#include "stdio.h"
#include "string.h"
#include "time.h"
#include "wait.h"
#include "sys/ipc.h"
#include "sys/msg.h"
#include "sys/shm.h"
#include "sys/sem.h"
#include "sys/stat.h"

struct Message
{
    long mtype;
    char mtext[1024];
};

pid_t mainProcessValue = 0;
int ready = 0;
int messageQueue;
int semid;

int semaphoreCreation(const char *pathname, int semaphoreValue)
{
    int semid;
    key_t key;

    key = ftok(pathname, 1);
    if ((semid = semget(key, 1, IPC_CREAT | S_IRUSR | S_IWUSR)) < 0)
        perror("semget");
    if (semctl(semid, 0, SETVAL, semaphoreValue) < 0)
        perror("semctl");

    return semid;
}

void semaphoreOperation(int semid, int op)
{
    struct sembuf operation;

    operation.sem_num = 0;
    operation.sem_op = op;
    operation.sem_flg = 0;

    if (semop(semid, &operation, 1) < 0)
        perror("semop");
}

void semaphoreDelete(int semid)
{
    semctl(semid, 0, IPC_RMID);
}

void starthandler(int sig)
{
    if (sig == SIGUSR1)
    {
        ready++;
    }
}

pid_t ursula(int pipe_id_rec, int pipe_id_send) 
{
    pid_t process = fork();
    if (process == -1)
    {
        exit(-1);
    }
    if (process > 0)
    {
        return process;
    }

    kill(mainProcessValue, SIGUSR1);

    int toVaccinate;
    read(pipe_id_rec, &toVaccinate, sizeof(int));
    printf("Ursula ennyit fog oltani: %d\n", toVaccinate);

    int vaccinated = 0;
    int i;

    // srand(getpid()) is seeding the random number generator with the current process ID. 
    //This is often done to ensure that the sequence of random numbers generated by rand() varies each time the program is run, making the random numbers less predictable. 
    srand(getpid());

    for(i = 0; i < toVaccinate; i++) {
        int chance = rand()%100;
        int success = (chance < 80);
        if(success != 0){
            vaccinated++;
        }
    }
    printf("Ursulanak ennyit sikerult beoltani: %d\n", vaccinated);
    printf("Ursula - Betegek, nem lehetett oltani: %d\n", toVaccinate-vaccinated);

    struct Message msg;
    msg.mtype = 5;
    sprintf(msg.mtext, "%d", toVaccinate-vaccinated);
    struct Message msgg;
    msgg.mtype = 6;
    sprintf(msgg.mtext, "%d", vaccinated);

    msgsnd(messageQueue, &msg, sizeof(msg.mtext), 0);
    msgsnd(messageQueue, &msgg, sizeof(msgg.mtext), 0);

    exit(0);
}

pid_t csormester(int pipe_id_rec, int pipe_id_send)
{
    pid_t process = fork();
    if (process == -1)
    {
        exit(-1);
    }
    if (process > 0)
    {
        return process;
    }

    kill(mainProcessValue, SIGUSR1);

    int toVaccinate;
    read(pipe_id_rec, &toVaccinate, sizeof(int));
    printf("Csormester ennyit fog oltani: %d\n", toVaccinate);

    int vaccinated2 = 0;
    int i;

    srand(getpid());

    for(i = 0; i < toVaccinate; i++) {
        int chance2 = rand()%100;
        int success2 = (chance2 < 80);
        if(success2 != 0){
            vaccinated2++;
        }
    }
    printf("Csormesternek ennyit sikerult beoltani: %d\n", vaccinated2);
    printf("Csormester - Betegek, nem lehetett oltani: %d\n", toVaccinate-vaccinated2);

    struct Message msg;
    msg.mtype = 5;
    sprintf(msg.mtext, "%d", toVaccinate-vaccinated2);
    struct Message msgg;
    msgg.mtype = 6;
    sprintf(msgg.mtext, "%d", vaccinated2);

    msgsnd(messageQueue, &msg, sizeof(msg.mtext), 0);
    msgsnd(messageQueue, &msgg, sizeof(msgg.mtext), 0);

    exit(0);
}

int main(int argc, char** argv)
{
    if (argc < 2)
	{
		puts("Missing argument!");
		exit(-1);
	}

    int status;
    key_t mainKey;
    mainProcessValue = getpid();
    signal(SIGUSR1, starthandler);

    mainKey = ftok(argv[0], 1);
    messageQueue = msgget(mainKey, 0600 | IPC_CREAT);
    if (messageQueue < 0)
    {
        perror("msgget");
        return -1;
    }

    semid = semaphoreCreation(argv[0], 1);

    int patients = atoi(argv[1]);
    int ursulanum = patients/2;
    int csormesternum = patients%2 + ursulanum;
    printf("ursulanum: %d, csormesternum: %d \n",ursulanum, csormesternum);

    int io_pipes[2];
    int succ = pipe(io_pipes);

    if(succ == -1){
        exit(-1);
    }

    int io_pipes1[2];
    int succ1 = pipe(io_pipes1);

    if(succ1 == -1){
        exit(-1);
    }

    int io_pipes2[2];
    int succ2 = pipe(io_pipes2);

    if(succ2 == -1){
        exit(-1);
    }

    int io_pipes3[2];
    int succ3 = pipe(io_pipes3);

    if(succ3 == -1){
        exit(-1);
    }

    pid_t child1_pid = ursula(io_pipes[0], io_pipes1[1]);
    pid_t child2_pid = csormester(io_pipes2[0], io_pipes3[1]);

    while (ready < 1)
        ;
    puts("Ursula keszen all az oltasra!");
    while (ready < 2)
        ;
    puts("Csormester keszen all az oltasra!");

    write(io_pipes[1], &ursulanum, sizeof(int));
    write(io_pipes2[1], &csormesternum, sizeof(int));

    int vaccinatedUrsula;
    int vaccinatedCsor;
    int sickUrsula;
    int sickCsor;

    struct Message msg;
    msgrcv(messageQueue, &msg, sizeof(msg.mtext), 5, 0);
    sickUrsula = atoi(msg.mtext);
    msgrcv(messageQueue, &msg, sizeof(msg.mtext), 6, 0);
    vaccinatedUrsula = atoi(msg.mtext);
    msgrcv(messageQueue, &msg, sizeof(msg.mtext), 5, 0);
    sickCsor = atoi(msg.mtext);
    msgrcv(messageQueue, &msg, sizeof(msg.mtext), 6, 0);
    vaccinatedCsor = atoi(msg.mtext);

    printf("Oltottak szama: %d\n", vaccinatedUrsula + vaccinatedCsor);
    printf("Betegek szama: %d\n", sickUrsula + sickCsor);

    semaphoreOperation(semid, -1);
    FILE *temp;
    temp = fopen("data.txt","a");
    if (temp == NULL)
    {
        fprintf(stderr, "\nError - cannot open the file\n");
        exit(1);
    }

    // struct tm structure representing the year (since 1900), month (0-11), and day of the month (1-31), respectively. 
    // Adding 1900 to tm.tm_year adjusts it to the current year, and adding 1 to tm.tm_mon adjusts it to the current month (since months in C are zero-indexed). 
    time_t t = time(NULL);
    struct tm tm = *localtime(&t);
    fprintf(temp,"Ezen a napon: %d-%d-%d\n", tm.tm_year + 1900, tm.tm_mon + 1, tm.tm_mday);
    fprintf(temp, "Oltasra erkezettekbol: %d ennyi kapott oltast:%d, ennyi nem: %d\n", patients, vaccinatedUrsula+vaccinatedCsor, patients-(vaccinatedUrsula+vaccinatedCsor));
    fclose(temp);
    semaphoreOperation(semid, 1);

    printf("Dr. Bubo befejezi a tevekenyseget.\n");

    waitpid(child1_pid, &status, 0);
    printf("Ursula - terminated with status: %d\n", status);
    waitpid(child2_pid, &status, 0);
    printf("Csormester - terminated with status: %d\n", status);
    close(io_pipes[0]);
    close(io_pipes[1]);
    close(io_pipes1[0]);
    close(io_pipes1[1]);
    close(io_pipes2[0]);
    close(io_pipes2[1]);
    close(io_pipes3[0]);
    close(io_pipes3[1]);
    status = msgctl(messageQueue, IPC_RMID, NULL);
    if (status < 0)
    {
        perror("msgctl");
    }
    semaphoreDelete(semid);
    return 0;
}